version: "3"
services:
  web:
    build: .
    image: marciaga/kffp-admin
    ports:
      - "3000"
    command: yarn start
    environment:
      NODE_ENV: production
    links:
      - db

  db:
    image: mongo
    ports:
      - "27017"

  server:
    image: marciaga/kffp-nginx
    build: ./docker/nginx
    ports:
      - "80:80"
    links:
      - web
