branch-defaults:
   master:
    environment: kffpadmin-prod
  develop:
    environment: kffpadmin-stage

global:
  application_name: kffp-admin
  default_ec2_keyname: KFFP_DEPLOY
  default_platform: Node.js
  default_region: us-west-2
  instance_profile: kffpadmin
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application

deploy:
  artifact: kffpadmin.zip
