branch-defaults:
  develop:
    environment: kffpadmin-stage
global:
  application_name: kffp-admin
  branch: null
  default_ec2_keyname: kffpadmin
  default_platform: Node.js
  default_region: us-west-2
  instance_profile: kffpadmin
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
